//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] AttachDataSignBehavior {
            get {
                object obj = ResourceManager.GetObject("AttachDataSignBehavior", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] AutoMapper {
            get {
                object obj = ResourceManager.GetObject("AutoMapper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] AutoMapper_Net4 {
            get {
                object obj = ResourceManager.GetObject("AutoMapper_Net4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 开始创建代码 的本地化字符串。
        /// </summary>
        internal static string BeginGenerate {
            get {
                return ResourceManager.GetString("BeginGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        /// 的本地化字符串。
        /// </summary>
        internal static string CodeIni {
            get {
                return ResourceManager.GetString("CodeIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Container {
            get {
                object obj = ResourceManager.GetObject("Container", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Container1 {
            get {
                object obj = ResourceManager.GetObject("Container1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ContextUnit {
            get {
                object obj = ResourceManager.GetObject("ContextUnit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data2Obj {
            get {
                object obj = ResourceManager.GetObject("Data2Obj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DBContext {
            get {
                object obj = ResourceManager.GetObject("DBContext", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DBContext1 {
            get {
                object obj = ResourceManager.GetObject("DBContext1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DbContextExtensions {
            get {
                object obj = ResourceManager.GetObject("DbContextExtensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Entities {
            get {
                object obj = ResourceManager.GetObject("Entities", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Entity {
            get {
                object obj = ResourceManager.GetObject("Entity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] EntityFramework {
            get {
                object obj = ResourceManager.GetObject("EntityFramework", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 代码生成 的本地化字符串。
        /// </summary>
        internal static string GenerateOutput {
            get {
                return ResourceManager.GetString("GenerateOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] IApplication {
            get {
                object obj = ResourceManager.GetObject("IApplication", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img {
            get {
                object obj = ResourceManager.GetObject("img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] IRepository {
            get {
                object obj = ResourceManager.GetObject("IRepository", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] IService {
            get {
                object obj = ResourceManager.GetObject("IService", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] IService1 {
            get {
                object obj = ResourceManager.GetObject("IService1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_Explorer_Application_CodeFirst_Seedwork {
            get {
                object obj = ResourceManager.GetObject("iTelluro_Explorer_Application_CodeFirst_Seedwork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_Explorer_Domain_CodeFirst_Seedwork {
            get {
                object obj = ResourceManager.GetObject("iTelluro_Explorer_Domain_CodeFirst_Seedwork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_Explorer_InfoUtility {
            get {
                object obj = ResourceManager.GetObject("iTelluro_Explorer_InfoUtility", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_Explorer_Infrastruct_CodeFirst_Seedwork {
            get {
                object obj = ResourceManager.GetObject("iTelluro_Explorer_Infrastruct_CodeFirst_Seedwork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_Explorer_Infrastructure_CrossCutting {
            get {
                object obj = ResourceManager.GetObject("iTelluro_Explorer_Infrastructure_CrossCutting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_Explorer_Infrastructure_CrossCutting_NetFramework {
            get {
                object obj = ResourceManager.GetObject("iTelluro_Explorer_Infrastructure_CrossCutting_NetFramework", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_SSO {
            get {
                object obj = ResourceManager.GetObject("iTelluro_SSO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_SSO_Common {
            get {
                object obj = ResourceManager.GetObject("iTelluro_SSO_Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_SSO_WebServices {
            get {
                object obj = ResourceManager.GetObject("iTelluro_SSO_WebServices", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_SYS_Entity {
            get {
                object obj = ResourceManager.GetObject("iTelluro_SYS_Entity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] iTelluro_Utility {
            get {
                object obj = ResourceManager.GetObject("iTelluro_Utility", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] log4net {
            get {
                object obj = ResourceManager.GetObject("log4net", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Map {
            get {
                object obj = ResourceManager.GetObject("Map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MethodApp {
            get {
                object obj = ResourceManager.GetObject("MethodApp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MethodIApp {
            get {
                object obj = ResourceManager.GetObject("MethodIApp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MethodIServer {
            get {
                object obj = ResourceManager.GetObject("MethodIServer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MethodServer {
            get {
                object obj = ResourceManager.GetObject("MethodServer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_Practices_Unity {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Practices_Unity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Profile {
            get {
                object obj = ResourceManager.GetObject("Profile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Profile1 {
            get {
                object obj = ResourceManager.GetObject("Profile1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Repository {
            get {
                object obj = ResourceManager.GetObject("Repository", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 D:\Entity2CodeModel 的本地化字符串。
        /// </summary>
        internal static string RootPath {
            get {
                return ResourceManager.GetString("RootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Service {
            get {
                object obj = ResourceManager.GetObject("Service", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Service1 {
            get {
                object obj = ResourceManager.GetObject("Service1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 失败! 的本地化字符串。
        /// </summary>
        internal static string StateFail {
            get {
                return ResourceManager.GetString("StateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string StateSuccess {
            get {
                return ResourceManager.GetString("StateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] UnityInstanceProvider {
            get {
                object obj = ResourceManager.GetObject("UnityInstanceProvider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] UnityInstanceProviderServiceBehavior {
            get {
                object obj = ResourceManager.GetObject("UnityInstanceProviderServiceBehavior", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] WebConfig {
            get {
                object obj = ResourceManager.GetObject("WebConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
